<a href="https://colab.research.google.com/github/serli2904/Tugas-Kuliah-Teknik-Pengambilan-Sampel-dan-Wrangling/blob/main/Serli_Sri_Lestari_241061022_Tugas_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import json
df = pd.read_csv('/content/student_data (1).csv')

In [7]:
df.head()
# Mengecek apakah data berhasil dimuat dengan benar, melihat nama kolom, dan memahami tipe data awal.

,GP,F,18,U,GT3,A,4,4.1,at_home,teacher,...,4.2,3,4.3,1,1.1,3.1,6,5,6.1,6.2
0,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
1,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
2,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
3,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
4,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15

In [8]:
df.info()
# Menampilkan ringkasan singkat atau "gambaran umum" dari sebuah DataFrame.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 394 entries, 0 to 393
Data columns (total 33 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GP       394 non-null    object
 1   F        394 non-null    object
 2   18       394 non-null    int64
 3   U        394 non-null    object
 4   GT3      394 non-null    object
 5   A        394 non-null    object
 6   4        394 non-null    int64
 7   4.1      394 non-null    int64
 8   at_home  394 non-null    object
 9   teacher  394 non-null    object
 10  course   394 non-null    object
 11  mother   394 non-null    object
 12  2        394 non-null    int64
 13  2.1      394 non-null    int64
 14  0        394 non-null    int64
 15  yes      394 non-null    object
 16  no       394 non-null    object
 17  no.1     394 non-null    object
 18  no.2     394 non-null    object
 19  yes.1    394 non-null    object
 20  yes.2    394 non-null    object
 21  no.3     394 non-null    object
 22  no.4     394 non-null    object
 23  4.2      394 non-null    int64
 24  3        394 non-null    int64
 25  4.3      394 non-null    int64
 26  1        394 non-null    int64
 27  1.1      394 non-null    int64
 28  3.1      394 non-null    int64
 29  6        394 non-null    int64
 30  5        394 non-null    int64
 31  6.1      394 non-null    int64
 32  6.2      394 non-null    int64
dtypes: int64(16), object(17)
memory usage: 101.7+ KB

In [9]:
df.shape
# Memberitahu jumlah baris dan jumlah kolom secara sekaligus.

(394, 33)

In [10]:
data_json = """
[
  {"id_produk": 201, "nama_barang": "Indomie Goreng Spesial", "kategori": "Mie Instan", "stok": 120, "harga": 3100},
  {"id_produk": 202, "nama_barang": "Minyak Goreng Bimoli 2L", "kategori": "Kebutuhan Dapur", "stok": 45, "harga": 38500},
  {"id_produk": 203, "nama_barang": "Ultra Milk Cokelat 250ml", "kategori": "Minuman", "stok": 60, "harga": 7200},
  {"id_produk": 204, "nama_barang": "Aqua Botol 600ml", "kategori": "Minuman", "stok": 200, "harga": 3500},
  {"id_produk": 205, "nama_barang": "Chitato Sapi Panggang", "kategori": "Makanan Ringan", "stok": 35, "harga": 11500},
  {"id_produk": 206, "nama_barang": "Sabun Lifebuoy Merah", "kategori": "Perawatan Tubuh", "stok": 50, "harga": 5000},
  {"id_produk": 207, "nama_barang": "Sedaap Mie Kuah Kari", "kategori": "Mie Instan", "stok": 85, "harga": 3000},
  {"id_produk": 208, "nama_barang": "Gulaku Kuning 1kg", "kategori": "Kebutuhan Dapur", "stok": 25, "harga": 17500},
  {"id_produk": 209, "nama_barang": "Pepsodent White 190g", "kategori": "Perawatan Tubuh", "stok": 40, "harga": 18200},
  {"id_produk": 210, "nama_barang": "Taro Net Seaweed", "kategori": "Makanan Ringan", "stok": 30, "harga": 9800}
]
"""

In [11]:
data_csv = json.loads(data_json)
# mengubah format teks (String) menjadi format data Python (seperti List atau Dictionary).

In [12]:
df = pd.DataFrame(data_csv)
# kemudian kita mengubah data ini ke pandas data frame
df.head()
# setelah itu kita mengecek 5 data teratas

   id_produk               nama_barang         kategori  stok  harga
0        201    Indomie Goreng Spesial       Mie Instan   120   3100
1        202   Minyak Goreng Bimoli 2L  Kebutuhan Dapur    45  38500
2        203  Ultra Milk Cokelat 250ml          Minuman    60   7200
3        204          Aqua Botol 600ml          Minuman   200   3500
4        205     Chitato Sapi Panggang   Makanan Ringan    35  11500

In [16]:
df.to_csv('data_indomaret.csv', index=False)
# dan terakhir kita mengubah data tersebut dan bisa disimpan